name: PassgoriExtension
description: Password storage using Nigori
dependencies:
  nigori:
    git: file:///home/drt24/dart/nigori/
  json_object:
    git: git://github.com/ucam-cl-dtg/dartwatch-JsonObject.git
  js: any
